### ISSUE TITLE
generalization to 3 dimensions

### ISSUE THREAD

**Issue by martinResearch** [atksh/python_prtree#14]
Hi, 
Thank you for this nice work. 
I love the fact it support batch query (unlike rtree https://github.com/Toblerity/rtree/issues/178). 
It would be great if it could support 3 dimensions (or maybe even n dimensions if that does not impact the speed). Does that seem easily feasible ? 
This could then potentially be used in the trimesh library to speed thing up and solve issue https://github.com/mikedh/trimesh/issues/1116

**Comment by atksh** [comment]
Hi,

It is feasible, but not easy due to the implementation of this library. This is because the four real numbers representing a two-dimensional rectangle are stored as fixed-length vectors in order to use SIMD. Plus, the building method of the Priority R-tree depends on the dimensions. 

Another way to build a 3d-prtree may be to use three 2d-prtrees, like xy, yz, zx projection planes. The query result could be the intersection of the three results. This can be implemented by c++.

**Comment by martinResearch** [comment]
ok, thank for the explanation! I believe it would need to be a real 3d rtree to allow efficient queries

**Comment by atksh** [comment]
@martinResearch 
It may be too late for you, but 3D Priority-RTree is now supported. Potentially any dimension can be supported.
