### ISSUE TITLE
Downgrade to Python 2.7

### ISSUE THREAD

**Issue by DynaBimm** [atksh/python_prtree#36]
Hi @atksh! 
Thanks for this extremely fast solution! Works fine in Python 3.8, but i have some outdated software with integrated Python 2.7. Is it possible to make version for IronPython 2.7? I can succsessfully use some dlls from other projects, but here we have pybind11. Tried to build it with latest pybind for python 2.7, had many errors. Thanks in advance!

**Comment by atksh** [comment]
Hi @DynaBimm,

Thank you for your feedback. I understand that you are looking for a solution for IronPython 2.7, however, due to compatibility issues with the latest version of pybind11, I am unable to support this version at this time. I apologize for any inconvenience this may cause.

If you have found a solution for pybind11 compatibility, please let me know. I am always open to exploring new ideas and finding ways to improve my solution.
